create table if not exists `orbit_data`
(
    `id`                          bigint primary key auto_increment not null,
    `reference_id`                varchar(256),
    `orbit_id`                    varchar(100),
    `orbit_determination_date`    varchar(100),
    `first_observation_date`      datetime,
    `last_observation_date`       datetime,
    `data_arc_in_days`            int,
    `observations_used`           int,
    `orbit_uncertainty`           int,
    `minimum_orbit_intersection`  double,
    `jupiter_tisserand_invariant` double,
    `epoch_osculation`            double,
    `eccentricity`                double,
    `semi_major_axis`             double,
    `inclination`                 double,
    `ascending_node_longitude`    double,
    `orbital_period`              double,
    `perihelion_distance`         double,
    `perihelion_argument`         double,
    `aphelion_distance`           double,
    `perihelion_time`             double,
    `mean_anomaly`                double,
    `mean_motion`                 double,
    `equinox`                     varchar(100),
    `orbit_class_type`            varchar(100),
    `orbit_class_description`     text,
    `orbit_class_range`           text,
    `created_at`                  datetime                          not null default current_timestamp,
    `updated_at`                  datetime on update current_timestamp,
    `deleted_at`                  datetime
);